# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'JogoDaMemoria' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JogoDaMemoria

  target 'JogoDaMemoriaTests' do
    inherit! :search_paths
    pod 'Nimble'
    pod 'Quick'
  end

  target 'JogoDaMemoriaUITests' do
    # Pods for testing
  end

end
